// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://votlredkpkiafedzkham.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvdGxyZWRrcGtpYWZlZHpraGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDgzMDUsImV4cCI6MjA2NTEyNDMwNX0.ggPcXfnLuhRVJb8Xf3N0A9TqbsuUvzu51mB2maz6SfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);